#!/usr/bin/env bash
# Ce script modifie le fichier /etc/hosts pour configurer localhost et facebook.com avec des adresses IP spécifiques

# Sauvegarde du fichier /etc/hosts
sudo cp /etc/hosts /etc/hosts.bak

# Modification de l'adresse IP de localhost à 127.0.0.2
sudo sed -i '/127.0.0.1\s\+localhost/d' /etc/hosts
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts

# Ajout de l'adresse IP pour facebook.com
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts

echo "Changements appliqués :"
echo "localhost => 127.0.0.2"
echo "facebook.com => 8.8.8.8"
